#define STRINGIFY(s) #s
#define QCSTR(str) STRINGIFY(str) 
#define QIK_INSTALLER_VERSION 1.0.159.4 //Latest version of QIK tool
#define QIK_PACKAGE_VERSION 1.00.93.0 //Install Shield version and QIK package version
#define QC_FILTER_FILE_VERSION 1,0,1,4
#define QC_FILTER_PRODUCT_VERSION 1.0.1.4
#define QC_FILTER_FILE_VERSION_STRING QCSTR(QC_FILTER_FILE_VERSION)
#define QC_FILTER_PRODUCT_VERSION_STRING QCSTR(QC_FILTER_PRODUCT_VERSION)
#define QC_NET_FILE_VERSION 5,0,1,0
#define QC_NET_PRODUCT_VERSION 5.0.1.0
#define QC_NET_FILE_VERSION_STRING QCSTR(QC_NET_FILE_VERSION)
#define QC_NET_PRODUCT_VERSION_STRING QCSTR(QC_NET_PRODUCT_VERSION)
#define QC_WDFSERIAL_FILE_VERSION 1,0,3,3
#define QC_WDFSERIAL_PRODUCT_VERSION 1.0.3.3
#define QC_WDFSERIAL_FILE_VERSION_STRING QCSTR(QC_WDFSERIAL_FILE_VERSION)
#define QC_WDFSERIAL_PRODUCT_VERSION_STRING QCSTR(QC_WDFSERIAL_PRODUCT_VERSION)
#define QDB_USB_FILE_VERSION 1,0,4,1
#define QDB_USB_PRODUCT_VERSION 1.0.4.1
#define QDB_USB_FILE_VERSION_STRING QCSTR(QDB_USB_FILE_VERSION)
#define QDB_USB_PRODUCT_VERSION_STRING QCSTR(QDB_USB_PRODUCT_VERSION)
#define QC_ADB_VERSION 1.0.1.6
