// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause

#define STRINGIFY(s) #s
#define QCSTR(str) STRINGIFY(str)
#define QCOM_USB_DRIVERS_PRODUCT_VERSION 1.00.94.2
#define QCOM_USB_DRIVERS_PRODUCT_VERSION_STRING QCSTR(QCOM_USB_DRIVERS_PRODUCT_VERSION)

#define QCOM_FILTER_VERSION 1.0.1.4
#define QCOM_FILTER_FILE_VERSION 1,0,1,4
#define QCOM_FILTER_FILE_VERSION_STRING QCSTR(QCOM_FILTER_VERSION)

#define QCOM_NET_VERSION 5.0.1.0
#define QCOM_NET_FILE_VERSION 5,0,1,0
#define QCOM_NET_FILE_VERSION_STRING QCSTR(QCOM_NET_VERSION)

#define QCOM_WDFSERIAL_VERSION 1.0.3.3
#define QCOM_WDFSERIAL_FILE_VERSION 1,0,3,3
#define QCOM_WDFSERIAL_FILE_VERSION_STRING QCSTR(QCOM_WDFSERIAL_VERSION)

#define QCOM_QDSS_VERSION 1.0.4.1
#define QCOM_QDSS_FILE_VERSION 1,0,4,1
#define QCOM_QDSS_FILE_VERSION_STRING QCSTR(QCOM_QDSS_VERSION)

#define QCOM_ADB_VERSION 1.0.1.6

#define QCOM_USB_DRIVERS_COMPANY_NAME "Qualcomm Technologies, Inc."
#define QCOM_USB_DRIVERS_PRODUCT_NAME "Qualcomm USB Kernel Drivers"
#define QCOM_USB_DRIVERS_COPYRIGHT "Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries."
